--TABLA USUARIO
--LLAVE PRIMARIA
ALTER TABLE USUARIOS ADD CONSTRAINT PK_ID_USUARIO
	PRIMARY KEY (ID_USER)

--LLAVE FORANEA
ALTER TABLE USUARIOS ADD CONSTRAINT FK_SEXO
	FOREIGN KEY (SEXO_USUARIO)
	REFERENCES SEXOS(ID_SEXO)

ALTER TABLE USUARIOS ADD CONSTRAINT FK_ROL
	FOREIGN KEY (ROL_USUARIO)
	REFERENCES ROLES(ID_ROL)
	
ALTER TABLE USUARIOS ADD CONSTRAINT FK_CARRERAS
	FOREIGN KEY (CARRERA_USUARIO)
	REFERENCES CARRERAS(ID_FACULTAD)
	
ALTER TABLE USUARIOS ADD CONSTRAINT FK_OCUPACION
	FOREIGN KEY (OCUPACION_USUARIO)
	REFERENCES OCUPACIONES(ID_OCUPACION)
	
ALTER TABLE USUARIOS ADD CONSTRAINT FK_EVENTO
	FOREIGN KEY (EVENTO)
	REFERENCES EVENTOS(ID_EVENTO)
	
--CAMPOS OBLIGATORIOS
ALTER TABLE USUARIOS ADD CONSTRAINT NN_NOMBRE
	CHECK (NOMBRE IS NOT NULL)

ALTER TABLE USUARIOS ADD CONSTRAINT NN_FECHA_NACIMIENTO
	CHECK(FECHA_NACIMIENTO IS NOT NULL)
	
ALTER TABLE USUARIOS ADD CONSTRAINT NN_CORREO_INSTITUCIONAL
	CHECK(CORREO_INSTITUCIONAL IS NOT NULL)
	
ALTER TABLE USUARIOS ADD CONSTRAINT NN_CONTRASENA
	CHECK(CONTRASEÑA IS NOT NULL)
	
ALTER TABLE USUARIOS ADD CONSTRAINT NN_CONTACTO
	CHECK(CONTACTO IS NOT NULL)
	
ALTER TABLE USUARIOS ADD CONSTRAINT NN_OCUPACION_USUARIO
	CHECK(OCUPACION_USUARIO IS NOT NULL)
	
ALTER TABLE USUARIOS ADD CONSTRAINT NN_SEXO_USUARIO
	CHECK(SEXO_USUARIO IS NOT NULL)
	
ALTER TABLE USUARIOS ADD CONSTRAINT NN_ROL
	CHECK(ROL_USUARIO IS NOT NULL)
	
ALTER TABLE USUARIOS ADD CONSTRAINT NN_EVENTO
	CHECK(EVENTO IS NOT NULL)
	
ALTER TABLE USUARIOS ADD CONSTRAINT NN_CARRERA_USUARIO
	CHECK(CARRERA_USUARIO IS NOT NULL)
	

--TABLA ROLES	

--LLAVE PRMARIA
ALTER TABLE ROLES ADD CONSTRAINT PK_ID_ROL
	PRIMARY KEY (ID_ROL)
--CAMPOS OBLIGATORIOS
ALTER TABLE ROLES ADD CONSTRAINT NN_NOMBRE_ROLES
	CHECK(NOMBRE_ROL IS NOT NULL)


--TABLA SEXOS 
-- LLAVE PRIMARIA 
ALTER TABLE SEXOS ADD CONSTRAINT PK_ID_SEXO
	PRIMARY KEY(ID_SEXO)
--CAMPOS OBLIGATORIOS
ALTER TABLE SEXOS ADD CONSTRAINT NN_NOMBRE_SEXO
	CHECK(NOMBRE_SEXO IS NO NULL)
	
--TABLA EVENTOS 
--LLAVE PRIMARIA
ALTER TABLE EVENTOS  ADD CONSTRAINT PK_ID_EVENTO
	PRIMARY KEY (ID_EVENTO)

--CAMPOS OBLIGATORIOS
ALTER TABLE EVENTOS ADD CONSTRAINT NN_EVENTOS
	CHECK(NOMBRE_EVENTO IS NOT NULL)
	

--TABLA OCUPACIONES
ALTER TABLE OCUPACIONES ADD CONSTRAINT PK_ID_OCUPACION
	PRIMARY KEY (ID_OCUPACION)
	
--CAMPOS OBLIGATORIOS
ALTER TABLE OCUPACIONES ADD CONSTRAINT NN_OCUPACION
	CHECK(NOMBRE_OCUPACION IS NOT NULL)
	
---TABLA CARRERAS
ALTER TABLE CARRERAS ADD CONSTRAINT PK_ID_CARRERA
	PRIMARY KEY (ID_OCUPACION)
---CAMPOS OBLIGATORIOS
ALTER TABLE CARRERA ADD CONSTRAINT NN_CARREAS
	CHECK(NOMBRE_CARRERA IS NOT NULL)
	



	
